// js/modules/drawing/drawing_notes.js
// Notes and abbreviations: the short words and standard notes found on
// drawings, in plain language.

import { makeDictionary } from './dictionary.js';

const ABBREVIATIONS = [
    { name: 'UOS', aka: '(unless otherwise specified; also UNLESS OTHERWISE STATED)',
      meaning: 'The rule that follows applies everywhere on the drawing, except where a dimension or note says something different.',
      example: '"FILLETS R0.5 UOS": every inside corner gets R0.5, except any corner with its own radius shown.' },
    { name: 'TYP', aka: '(typical)',
      meaning: 'This dimension or note applies to all the features that look the same, not just the one it points to.',
      example: '"R2 TYP" on one corner of a plate: all four matching corners are R2.',
      watch: 'It is not always obvious which features count as "the same". If unsure, ask; modern drawings prefer "4X R2" instead.' },
    { name: 'nX', aka: '(2X, 4X ...)',
      meaning: 'The number of times the feature appears. The callout applies to each one.',
      example: '"4X Ø6.6 THRU": four through holes, each Ø6.6.' },
    { name: 'REF', aka: '(reference dimension, or a number in brackets)',
      meaning: 'A dimension given for information only. It has no tolerance and is not inspected.',
      example: '(120) as an overall length when the pieces that add up to it are already dimensioned.',
      watch: 'Do not make or reject a part based on a reference dimension.' },
    { name: 'BSC', aka: '(basic)',
      meaning: 'An exact, perfect value, usually shown as a number in a box. The allowed error comes from a GD&T frame.',
      see: ['CHARACTERISTICS', 'position', 'Position'] },
    { name: 'THRU',
      meaning: 'The hole or slot goes all the way through the part.',
      example: '"Ø8 THRU" is a drilled hole that comes out the other side.' },
    { name: 'DP', aka: '(depth; also the ↧ symbol)',
      meaning: 'How deep a hole or pocket goes, measured to the end of the full diameter, not to the drill point.',
      example: '"Ø6 ↧12" is a Ø6 hole 12 deep, plus the cone left by the drill.',
      see: ['DECODE', 'hole_callouts', 'Holes, threads & patterns'] },
    { name: 'CBORE, CSK, SF', aka: '(counterbore, countersink, spotface)',
      meaning: 'Shapes cut at the top of a hole: a flat-bottom step for a screw head (counterbore), a cone for a flat-head screw (countersink), or a shallow flat seat (spotface).',
      see: ['DECODE', 'hole_callouts', 'Holes, threads & patterns'] },
    { name: 'EQ SP', aka: '(equally spaced)',
      meaning: 'The features are spaced evenly. Often used for holes around a circle.',
      example: '"6X Ø9 EQ SP ON Ø80 BC": six holes, 60° apart, on an 80 mm circle.' },
    { name: 'BC, BCD, PCD', aka: '(bolt circle, pitch circle diameter)',
      meaning: 'The diameter of the circle that the centres of a ring of holes sit on.' },
    { name: 'R, CR, SR, SØ', aka: '(radius, controlled radius, spherical radius, spherical diameter)',
      meaning: 'R is a radius. CR is a tighter radius: the curve must be smooth, with no flats or reversals. SR and SØ are for ball shapes.',
      watch: 'CR is stricter than R, even with the same numbers.' },
    { name: 'MAX / MIN',
      meaning: 'Only one limit is given. The other side is open (but must still make sense).',
      example: '"R0.5 MAX" corner radius: anything from sharp up to 0.5 is fine.' },
    { name: 'THK', aka: '(thickness)',
      meaning: 'The thickness of a plate or sheet part.',
      example: '"3 THK" under the view of a sheet-metal bracket.' },
    { name: 'ID / OD', aka: '(inside / outside diameter)',
      meaning: 'The inside or outside diameter of a tube, ring or bore.' },
    { name: 'FIM / TIR', aka: '(full indicator movement / total indicator reading)',
      meaning: 'The total swing of a dial indicator, highest reading minus lowest. Used for runout.',
      see: ['CHARACTERISTICS', 'circular_runout', 'Circular runout'] },
    { name: 'SIM', aka: '(similar)',
      meaning: 'This feature is like another one shown, but not identical. Check which parts differ.' },
    { name: 'OPP HAND', aka: '(opposite hand, mirror)',
      meaning: 'A second part that is the mirror image of the one drawn, like a left and a right bracket.',
      watch: 'Mirror parts need their own part numbers. Mixing them up is a classic mistake.' },
    { name: 'NTS', aka: '(not to scale)',
      meaning: 'This view or dimension is not drawn to the sheet\'s scale. The number is still correct.' },
    { name: 'CL, ℄', aka: '(centre line)',
      meaning: 'Marks a centre line or the middle of a symmetric part.' }
];

const NOTES = [
    { name: 'Break sharp edges', aka: '(BSE, break all sharp edges 0.2-0.5)',
      meaning: 'Every edge without a chamfer or radius shown gets a small chamfer or radius, so it is not razor sharp.',
      example: '"BREAK SHARP EDGES 0.2-0.5": a light chamfer 0.2 to 0.5 mm on every edge.',
      watch: 'It applies to all edges, including inside hole edges, unless the note says "outside edges only".' },
    { name: 'Remove all burrs', aka: '(deburr)',
      meaning: 'Remove the small rough bits of metal left by cutting tools. No loose or raised material may remain.',
      watch: 'Burrs inside cross holes are easy to miss and can cause failures in hydraulic or moving parts.' },
    { name: 'Dimensions apply after coating', aka: '(or before plating)',
      meaning: 'Says whether the sizes are checked with the coating on or off. It changes what size the machinist aims for.',
      example: 'A Ø10.00 +0.02 hole with "APPLIES AFTER ANODIZE" must be machined slightly bigger, because the coating makes it smaller.',
      see: ['DECODE', 'title_block', 'Title block: finish'] },
    { name: 'Mask', aka: '(mask threads / mask surfaces)',
      meaning: 'Cover these areas so no coating or paint goes on them.',
      example: '"MASK ALL THREADS AND SURFACE A BEFORE PAINT".' },
    { name: 'Fillets and rounds', aka: '(ALL FILLETS R1 UOS)',
      meaning: 'The size of every inside corner (fillet) and outside corner (round) that has no radius shown.' },
    { name: 'Finish all over', aka: '(FAO)',
      meaning: 'Every surface must be machined. Mostly seen on castings and forgings.',
      see: ['DECODE', 'surface_finish', 'Surface finish'] },
    { name: 'Surface finish unless specified',
      meaning: 'The default surface roughness for all machined surfaces without their own finish symbol.',
      example: '"SURFACE FINISH Ra 3.2 UOS": every machined face must be Ra 3.2 or smoother, unless marked.',
      see: ['DECODE', 'surface_finish', 'Surface finish'] },
    { name: 'Part marking',
      meaning: 'Where and how to mark the part number, revision or serial number (ink, laser, stamp, tag).',
      watch: 'Stamping can distort thin parts. Follow the method named in the note.' },
    { name: 'Heat treat', aka: '(harden, stress relieve)',
      meaning: 'A heat process to change hardness or relieve stress, usually with a hardness range like 58-62 HRC.',
      watch: 'Check the order: some features must be finished after heat treatment because the part moves or grows.' },
    { name: 'Interpret per', aka: '(e.g. INTERPRET PER ASME Y14.5-2018)',
      meaning: 'Names the standard used to read the drawing. It decides how GD&T and sizes are understood.',
      see: ['DECODE', 'title_block', 'Title block: standard'] },
    { name: 'Do not scale drawing', aka: '(DNSD)',
      meaning: 'Do not measure the paper with a ruler to get a size. Use only written dimensions.',
      watch: 'If a size is missing, ask. Never guess by measuring the print.' },
    { name: 'Flag notes', aka: '(a number in a triangle or flag)',
      meaning: 'A note that applies only where its flag symbol is placed on the drawing. The note text is in the notes list with the same number.',
      example: 'A triangle with 5 next to a surface points to note 5: "NO TOOL MARKS ALLOWED ON THIS SURFACE".' },
    { name: 'Critical or key characteristic', aka: '(KC, CC, a diamond or shield symbol)',
      meaning: 'A dimension the customer marks as extra important, often requiring more checks or process control (like SPC).',
      watch: 'Each company uses its own symbol. The notes or the quality requirements explain it.' }
];

const dict = makeDictionary({
    id: 'drawing_notes',
    kicker: 'Drawing basics',
    title: 'Notes & abbreviations',
    intro: 'Drawings use <b>short words</b> to save space, and the <b>notes</b> list rules that apply to the whole part. A general note counts just as much as a dimension: skipping one can make a good-looking part scrap.',
    placeholder: 'e.g. TYP, REF, burrs',
    groups: [{ name: 'Abbreviations', entries: ABBREVIATIONS }, { name: 'Common notes', entries: NOTES }],
    tip: 'Read every note before you start, not after. Notes often hold the rules that affect every feature, like edge breaks, coatings and default finishes.'
});

export const { draw, loadControls, unload } = dict;
export { ABBREVIATIONS, NOTES };
